version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pinked_user_interface
    environment:
      - AUTH0_SECRET=${AUTH0_SECRET}
      - AUTH0_BASE_URL=${AUTH0_BASE_URL}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - NEXT_PUBLIC_RESPONSE_CREATION_AGGREGATION_API=${NEXT_PUBLIC_RESPONSE_CREATION_AGGREGATION_API}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - 3000:3000
    networks:
      - pinked
    env_file:
      - .env

  response_creation_aggregation:
    build: 
      context: ./response_creation_aggregation
      dockerfile: Dockerfile
    container_name: response_creation_aggregation
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "30500:5000"
    restart: always
    volumes:
      - "./response_creation_aggregation:/project"
    networks: 
      - pinked
    env_file:
      - .env


  chromadb:
    image: chromadb/chroma:0.4.25.dev21
    container_name: chroma
    ports:
      - "8000:8000"  # Adjust the port as needed
    env_file:
      - .env
    networks: 
      - pinked

networks:
  pinked:
    driver: bridge