version: '3'

services:
  frontend:
    environment:
      - AUTH0_SECRET=${AUTH0_SECRET}
      - AUTH0_BASE_URL=http://34.127.82.55/
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
    ports:
      - 80:3000