version: '3'

services:
  response_creation_aggregation:
    build: 
      context: ./response_creation_aggregation
      dockerfile: Dockerfile
    container_name: response_creation_aggregation
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=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
    ports:
      - "30500:5000"
    restart: always
    volumes:
      - "./response_creation_aggregation:/project"
    networks: 
      - vector_stores
      - talkaroo

  chromadb:
    image: chromadb/chroma
    container_name: chroma
    networks:
      - vector_stores
    ports:
      - "8000:8000"  # Adjust the port as needed

networks:
  talkaroo:
    driver: bridge

  vector_stores:
    external: True