version: '3'

services:
  response_creation_aggregation:
    build: 
      context: ./response_creation_aggregation
      dockerfile: Dockerfile.dev
    container_name: response_creation_aggregation
    environment:
      - PYTHONUNBUFFERED=1
      - JUPYTER_TOKEN=project
    ports:
      - "58488:8888"
      - "58406:6006"
      - "58450:5000"
    restart: always
    volumes:
      - "./response_creation_aggregation:/project"
    networks: 
      - pinked
    env_file:
      - .env
      - .env.dev

  dashboard:
    build: 
      context: ./dashboard_backend
      dockerfile: Dockerfile.dev
    container_name: dashboard
    environment:
      - PYTHONUNBUFFERED=1
      - JUPYTER_TOKEN=project
    ports:
      - "57488:8888"
    restart: always
    volumes:
      - "./dashboard_backend:/project"
    networks: 
      - pinked
    env_file:
      - .env
      - .env.dev

networks:
  pinked:
    driver: bridge